### ISSUE TITLE
Prepare to meet with OnShape

### ISSUE THREAD

**Issue by ethan92429** [AguaClara/onshape#5]
# AguaClara Overview:

Water treatment plants scale with design flow rate. This means that hundreds of parameters can change with even small adjustments in flow rate. The adjustments change according to complex hydraulic equations that are *currently* resolved in Python. the resulting "physical parameters" that satisfy the hydraulic parameters are passed to CAD. Some CAD software draws the resulting plant. This was originally done in MathCAD and AutoCAD in place of Python and OnShape. The switch came because the old process was too difficult for students to maintain. Designing and integrating parts became prohibitively complex. However, this old system did successfully design 14 treatment plants currently built in Honduras. 

Challenges with the old system:
* took 10+ minutes to test a new design or any change to the design
* no automated testing 
* To insert an elbow, for instance, you had to work within the global coordinate space - adding up many dimensions. This was error prone and time consuming.
* Relied on outdated, buggy MathCAD software
* Didn't take advantage of modern parametric design principles

****************************************************************

# Current approach with Fusion: 
1. Generate a nested YAML with all physical parameters listed.
2. Upload the YAML to the Fusion document by cycling through the parameters of each included part.
3. The parts update. So we have to manually update the higher level parts to use the new version of the linked parts. This often breaks. 

Issues:
* Fusion parameters are far more limited than OnShape configurations. Parameters just support quantities. 
* Fusion has poor performance since cycling through every parameter is computationally intensive.
* Fusion has strange parameters scaling performance. Parameter variables aren't placed within the timeline, causing weird effects within sketches occasionally. 
* Fusion doesn't easily support link sharing, meaning we had to upload the design manually to a GitHub repo and write some code within our plugin to pull it manually.
* No built-in BOM or FeatureScript.

****************************************************************

### Assembly Pros:
- easy to connect parts manually 
- reduces feature list size, perhaps making parts more manageable
- perhaps performance pros to using assemblies over large part studios?
- Support in-context editing, allowing information to flow from an assembly to a part within the assembly.

### Assembly Cons:
- not possible to connect parts parametrically. what happens when we switch from one filter type to another? How do you dynamically "select" another part to be imported in? No "assembly configurations".

# Programming Questions:
* Is cycling through the YAML and uploading key-value pairs for each mentioned particular component a sound approach? I would edit the "derived part" feature to include the configuration outlined within the YAML. 

# Modeling Questions:
* Within assemblies, what is best practice for selecting different configurations? Assemblies don't have configurations, so what is best practice for dynamically adding and removing subassemblies/ configured parts? For example, say I want to add 
* How do I make a "reactive component"? One that can scale according to the assembly I put it in? For instance, when I put a pipe within a tank, and I want it to "auto-scale" from one fitting to another without having to specify the length? Should I be using in-context design? Is there any way to "auto-update" contexts?
* Why don't mates move with transforms in multi-part studios?
* Any way to specify functions instead of variables? define a function like headloss. This would live in the feature list... But that would discourage reusability.
* Tell me more about "routing"...

**Comment by monroews** [comment]
Can it handle the LFOM with i rows with j(i) holes in each row?
The designs you suggest showing should provide a good context for the discussion.

**Comment by ethan92429** [comment]
I met with OnShape last Friday. They had the following suggestions:
* **Don't write much python.** Try to include all logic within featureScript. Python can be used to produce the small set of dimensions that are directly determined by hydraulic equations. We need to precisely define this set. I don't think a clear set for the plant has been developed. My proposal is we think of the minimum set that will allow scaling between 12 and 60 L/s. Then, as we need more adjustability, we can "hand over" parameters to python to control. An example is the sed tank pipe. By allowing OnShape to _always_ use a 5 m long lance of 8" tubing, we eliminate the need to calculate any of the hydraulics. Indeed, all we need to specify is the number of sed tanks. This sparse list will be the interface, so to speak, between python and onshape. [I'm starting a sparse list here.](https://github.com/AguaClara/aide_render/issues/4)
* **Use master sketches** for determining global placement of unit processes. These sketches can have mate connectors built in that abide sketch constraints as needed.
* **Build reusable features** when needing special geometry. This way we can utilize FeatureScripts purpose-built design. _much_ faster than Fusion.
